import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from '../components/Header';
import Footer from '../components/Footer';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="منصة دار الزواج: تعارف وزواج بنات عربيات. اكتشف ملفات شخصية مشوقة، مقالات، وتجربة مستخدم ممتازة." />
        <meta name="keywords" content="زواج, تعارف, بنات عرب, شريكة حياة, الزواج في الخليج, الزواج في المغرب, الزواج في الجزائر, الزواج في تونس, الزواج في السعودية" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&family=Cairo:wght@400;700&display=swap" rel="stylesheet" />
        <title>دار الزواج - منصة تعارف وزواج بنات عربيات</title>
      </head>
      <body style={{ fontFamily: 'Cairo, Amiri, sans-serif' }} className="bg-gray-50 min-h-screen flex flex-col">
        <Header />
        <main className="flex-1 w-full max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
